name: Build Firmware

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi build-essential cmake

    - name: Setup Pico SDK
      run: |
        git clone --depth 1 --branch master https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init --depth 1
        echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

    - name: Build Project
      run: |
        # Ищем, в какой именно папке лежит CMakeLists.txt, и собираем прямо там
        TARGET_DIR=$(find . -name "CMakeLists.txt" -printf '%h\n' | head -n 1)
        echo "Found CMakeLists in $TARGET_DIR"
        cd "$TARGET_DIR"
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PicoFly-Firmware
        path: |
          **/build/*.uf2
          **/build/*.bin
